### ISSUE TITLE
Last time we had issue tracking, it sucked

### ISSUE THREAD

**Issue by taisel** [taisel/IodineGBA#1]
Let's figure out a better way to format this.

**Comment by eligrey** [comment]
Why did you reset this repo?

**Comment by taisel** [comment]
Linking someone's derivation of your own project isn't you writing the derivation. Same goes for someone linking to the piratebay, but not being the seeder or the piratebay itself.

**Comment by eligrey** [comment]
Why did you link to it if you knew it was illegal?

**Comment by taisel** [comment]
I found it interesting, was not thinking about legality when linking it.

**Comment by taisel** [comment]
If you don't mind I'd rather take this off the issue tracker and kept on email, if we're doing a Q/A. I do want to keep bug reports for the actual project in here.
