### ISSUE TITLE
Pokemon series wont save

### ISSUE THREAD

**Issue by fOmey** [taisel/IodineGBA#21]
Game's seems to run fine, although wont save.

I have tried: Pokemon Fire Red, Leaf Green, Emerald.. 

A way around this problem for a Windows GBA emulator is to change the save flash type: Save Type -> Flash 128K.

**Comment by taisel** [comment]
Those actually save for me.

**Comment by taisel** [comment]
What browser are you using? Also inspect the save export file to see if the browser is retaining it in html5 local storage before export.

**Comment by taisel** [comment]
>removes try/catches and adds an alert(error) to see if anything funny happens
> gets some weird af error code
> sees brand new user bug report

https://bugzilla.mozilla.org/show_bug.cgi?id=1238354

**Comment by fOmey** [comment]
Very weird, it just so happens its saving again.. might of been a issue with the rom I was using at the time of initial testing.

**Comment by taisel** [comment]
Which is even weirder that I so happened to have just run into that firefox bug.

**Comment by taisel** [comment]
Also, if you store too much in localStorage, browsers tend to reject further storage into it.
