### ISSUE TITLE
LDM mode change wrongly forces user bank transfer

### ISSUE THREAD

**Issue by DavidGoldman** [taisel/IodineGBA#22]
According to the ARM7TDMI manual, 

"LDM with R15 in transfer list and S bit set (Mode changes)
If the instruction is a LDM then SPSR_<mode> is transferred to CPSR at the same
time as R15 is loaded."

Current implementation forces user bank transferring at the same time.

**Comment by taisel** [comment]
https://github.com/taisel/IodineGBA/commit/de443a3825f6d375ed3ff6d658a640e1f5b6c40d
