### ISSUE TITLE
Land graphics I/O proxy

### ISSUE THREAD

**Issue by taisel** [taisel/IodineGBA#47]
For easier multi-threading of the emulator, as well as general clean separation principles.

**Comment by taisel** [comment]
This requires tampering with a lottttttt of individual i/o register handling.

**Comment by taisel** [comment]
Will be adding 16 and 32 bit wide handling as well, to speed shit up.

**Comment by taisel** [comment]
FYI, the graphics *state machine* was separated already. It's the physical graphics renderer that needs proper i/o proxying now.

**Comment by taisel** [comment]
I swear I treat iodinegba sometimes like my personal playground like I'm the only user, breaking shit and making unstable implementation and bugfix timelines.

*crickets*

**Comment by taisel** [comment]
Yeah this is gonna take a bit of time. Rewriting the entire way the renderer interfaces with the i/o address range reading and writing.

**Comment by taisel** [comment]
May be able to allow asm.js moduling for graphics renderer with this while everything else is strict mode js.

**Comment by TazeTSchnitzel** [comment]
Would this mean you could have the emulator running in a web worker?

**Comment by taisel** [comment]
Only if sharedarraybuffer is supported to  not encounter a bottleneck.

**Comment by taisel** [comment]
Also, this is about the renderer, not the emulator as a whole.

**Comment by taisel** [comment]
Hopefully allowing alternative renderers to be easily switched in should be a thing after this for sure. It's being nasty atm with a lot of touch ups around the entire i/o.

**Comment by taisel** [comment]
There's some more work I want to do, but we got our paths rewritten for the most part.
