### ISSUE TITLE
Rooms?

### ISSUE THREAD

**Issue by alansystem** [taisel/IodineGBA#50]
Where can rooms?

**Comment by TazeTSchnitzel** [comment]
Do you mean ROMs? This is not the place.

**Comment by alansystem** [comment]
but where can I find?

2015-05-27 19:44 GMT-03:00 Andrea Faulds <notifications@github.com>:

> Do you mean ROMs? This is not the place.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taisel/IodineGBA/issues/50#issuecomment-106101415>.
>



-- 
Alan Nogueira

**Comment by taisel** [comment]
Wut
