### ISSUE TITLE
Clean up filenames

### ISSUE THREAD

**Issue by taisel** [taisel/IodineGBA#51]
They're a bit long..

**Comment by taisel** [comment]
Combining this with the graphics i/o proxy crap being worked on.

**Comment by TazeTSchnitzel** [comment]
`IodineGBA/IodineGBA/IodineGBA/GameBoyAdvance` *is* a bit excessive

**Comment by taisel** [comment]
Yeah, I already removed the prefix "GameBoyAdvance" and suffix "Core" from most files on my local copy. I might rename the lowest IodineGBA folder as "core".

**Comment by TazeTSchnitzel** [comment]
Ah, I see things have been greatly improved. :)
